# Generated by Django 4.0.5 on 2022-07-11 04:38

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Project Status',
            },
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='Company.projectstatus'),
        ),
    ]
