# Generated by Django 4.0.5 on 2022-07-11 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_projectstatus_alter_ourproject_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourproject',
            old_name='status',
            new_name='project_status',
        ),
    ]
