# Generated by Django 4.0.5 on 2022-07-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_rename_status_ourproject_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproject',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Development', 'In Development')], default='Completed', max_length=20),
        ),
    ]
