# Generated by Django 4.0.5 on 2022-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_socialmediahandle_stat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourproject',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Development', 'In Development')], max_length=20, null=True),
        ),
    ]
