# Generated by Django 4.0.5 on 2022-07-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_alter_ourproject_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
