# Generated by Django 4.0.5 on 2022-07-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_delete_projectstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Project Status',
            },
        ),
    ]
