# Generated by Django 4.0.5 on 2022-07-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_projectstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
