# Generated by Django 4.0.5 on 2022-07-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0009_delete_projectstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobStat',
        ),
        migrations.DeleteModel(
            name='SocialMediaUrls',
        ),
    ]
